# Generated by Django 5.0 on 2025-07-29 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_organizationtype_key'),
        ('poultry_inspection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='page',
        ),
        migrations.RemoveField(
            model_name='role',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='role',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userrelations',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userrelations',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='userrelations',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userrelations',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrelations',
            name='user',
        ),
        migrations.CreateModel(
            name='Poultry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('creator_info', models.CharField(max_length=100, null=True)),
                ('modifier_info', models.CharField(max_length=100, null=True)),
                ('trash', models.BooleanField(default=False)),
                ('Lat', models.FloatField(null=True)),
                ('Long', models.FloatField(null=True)),
                ('unit_name', models.CharField(max_length=50, null=True)),
                ('fullname', models.CharField(max_length=250, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('breeding_unique_id', models.CharField(max_length=50, null=True)),
                ('quantity', models.BigIntegerField(default=0)),
                ('losses', models.BigIntegerField(default=0)),
                ('left_over', models.BigIntegerField(null=True)),
                ('killed_quantity', models.BigIntegerField(default=0)),
                ('hall', models.IntegerField(default=0)),
                ('date', models.DateTimeField(null=True)),
                ('chicken_breed', models.CharField(max_length=200, null=True)),
                ('period', models.BigIntegerField(default=0, null=True)),
                ('chicken_age', models.IntegerField(default=1)),
                ('total_losses', models.BigIntegerField(default=0)),
                ('licence_number', models.CharField(max_length=20, null=True)),
                ('health_certificate', models.CharField(max_length=100, null=True)),
                ('samasat_discharge_percentage', models.IntegerField(default=0)),
                ('PersonTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('InteractTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('UnionTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('CertId', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poultry_city', to='authentication.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createddby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poultry_province', to='authentication.province')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoultryInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('creator_info', models.CharField(max_length=100, null=True)),
                ('modifier_info', models.CharField(max_length=100, null=True)),
                ('trash', models.BooleanField(default=False)),
                ('business_license', models.CharField(max_length=100, null=True)),
                ('business_license_issuer', models.CharField(max_length=100, null=True)),
                ('licence_number', models.IntegerField(default=0)),
                ('registration_number', models.IntegerField(default=0)),
                ('economic_code', models.IntegerField(default=0)),
                ('type_of_ownership', models.CharField(max_length=250, null=True)),
                ('unit_type', models.CharField(max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createddby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('poultry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poultry_inspection', to='poultry_inspection.poultry')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_inspection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRelations',
        ),
    ]
