# Generated by Django 5.0 on 2025-07-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry_inspection', '0002_remove_permissions_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultryinspection',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
