# Generated by Django 5.0 on 2025-08-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry_inspection', '0003_poultryinspection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultryinspection',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
