# Generated by Django 5.0 on 2025-07-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_herd_owner',
        ),
    ]
