# Generated by Django 5.0 on 2025-07-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_user_is_herd_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='page',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userrelations',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
