# Generated by Django 5.0 on 2025-07-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_permissions_category_user_visible_password_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='province',
            new_name='province_id',
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='tel_prefix',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
