# Generated by Django 5.0 on 2025-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtype',
            name='key',
            field=models.CharField(choices=[('EMP', 'empty'), ('J', 'Jihad'), ('U', 'Union'), ('CO', 'Cooperative'), ('CMP', 'Companies')], default='J', max_length=3),
        ),
    ]
