# Generated by Django 5.0 on 2025-08-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_organizationtype_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
