# Generated by Django 5.0 on 2025-07-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='type_of_ownership',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='unit_type',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
