# Generated by Django 5.0 on 2025-07-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_inspection_type_of_ownership_inspection_unit_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
